apiVersion: v1
kind: ServiceAccount
metadata:
  name: tls-key-agent
  namespace: default
  labels:
    app: tls-key-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-key-agent
  labels:
    app: tls-key-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tls-key-agent
  labels:
    app: tls-key-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tls-key-agent
subjects:
- kind: ServiceAccount
  name: tls-key-agent
  namespace: default