[workspace]
members = [
    "cargo_mod", 
    "rust_deref_trait",
    "minigrep", 
    "restaurant",
    "rust_adder",
    "rust_array",
    "rust_enum",
    "rust_hashmap",
    "rust_if_let",
    "rust_lifetime",
    "rust_loop",
    "rust_match",
    "rust_method",
    "rust_ownership",
    "rust_ownership_2",
    "rust_rectangles",
    "rust_reference",
    "rust_result",
    "rust_slice",
    "rust_split_module",
    "rust_str",
    "rust_trait",
    "rust_trait2",
    "rust_trait3",
    "rust_trait4",
    "rust_trait5",
    "rust_use",
    "rust_vec", "rust_drop_trait", "rust_rc", "rust_refcell", "slist", "iter_test", "rust_19_3_match",
]
